name: ReleaseZip

on:
  push:
    branches:
      -  github-actions-tobuild-and-push-zip-to-s3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash ZipCode.sh testbucket2700 "/tmp/penny/penny.zip" ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "penny.zip"
